image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - dist
  - build

dist:
  stage: dist
  script:
    - echo "//nexus.wynd.eu/repository/npm/:_authToken=${NPM_TOKEN}" >> .npmrc
    - echo "//nexus.wynd.eu/repository/npm-hosted/:_authToken=${NPM_TOKEN}" >> .npmrc
    - yarn
    - yarn dist
  artifacts:
    expire_in: 1 day
    paths:
    - src/pos/dist/*
    - src/loader/dist/*
    - .npmrc

build:
  stage: build
  script:
    - yarn global add electron-builder
    - yarn build --publish always
    - rm -rf node_modules/
