stages:
  - dist
  - build


dist:
  stage: dist
  script:
    - npm run dist
  artifacts:
    paths:
    - src/pos/dist
    - src/loader/dist

build:
  stage: build
  script:
    - npm run build --publish always
