image: node:latest

cache:
  paths:
    - node_modules/
stages:
  - dist
  - build

dist:
  stage: dist
  script:
    - yarn
    - yarn dist
  artifacts:
    expire_in: 1 day
    paths:
    - src/pos/dist/*
    - src/loader/dist/*

build:
  stage: build
  script:
    - yarn
    - yarn global add electron-builder
    - yarn build --publish always
    - rm -rf node_modules/
