image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - dist
  - build

dist:
  stage: dist
  script:
    - echo "//nexus.wynd.eu/repository/npm/:_authToken=${NPM_TOKEN}" >> .npmrc
    - echo "//nexus.wynd.eu/repository/npm-hosted/:_authToken=${NPM_TOKEN}" >> .npmrc
    - npm i
    - npm run dist
  artifacts:
    expire_in: 1 day
    paths:
    - src/pos/dist/*
    - src/loader/dist/*

build:
  stage: build
  script:
    - npm run i -g electron-builder
    - npm run build -- --publish always
