var url_customer_display = "http://127.0.0.1:85/customer-display";
var url_pos = "http://localhost:9963"
// var url_pos = "http://sco2.decathlonqacentral.wyndstore.fr/login"
var url_api = "http://127.0.0.1:81/api";
var is_customer_display = 0;
var link_wptls = "/home/ppetit/nodejs/wyndpostools";
var printer_margin = 2;
var homemessage = "TOUCH TO START";
var phone_number = "+33 (0)1.76.44.03.53";
var city_weather = 0;
var chrome_printer = 0;
var wyndpostools = 1;
var launcher = "C:\\Program Files\\NW\\app\\launch_startNW.bat";
var shutdownpass = "1111";
var panel = 1;
var emergencyactivation = 1;
