
	const CODE = {
		CONNECTION_TIMEOUT: 'CONNECTION_TIMEOUT',
		MISSING_MANDATORY_PARAMETER: 'MISSING_MANDATORY_PARAMETER',
		GENERIC: 'INTERNAL_ERROR',
		APP_NOT_INITIALIZED: 'APP_NOT_INITIALIZED',
		SERVICE_NOT_STARTED: 'SERVICE_NOT_STARTED',
		SERVICE_$$_NOT_AVAILABLE: 'SERVICE_$$_NOT_AVAILABLE',
		INVALID_PARAMETERS: 'INVALID_PARAMETERS',
		MISSING_PARAMETER: 'MISSING_PARAMETER',
		$$_UNAUTHORIZED_$$: '$$_UNAUTHORIZED_$$',
		INVALID_TYPE_PARAMETER: 'INVALID_TYPE_PARAMETER',
		INVALID_FORMAT_PARAMETER: 'INVALID_FORMAT_PARAMETER',
		OUT_OF_RANGE_PARAMETER: 'OUT_OF_RANGE_PARAMETER',
		INVALID_FORMAT_UPPERCASE_PARAMETER: 'INVALID_FORMAT_UPPERCASE_PARAMETER',
		INVALID_FORMAT_DIGIT_PARAMETER: 'INVALID_FORMAT_DIGIT_PARAMETER',
		INVALID_FORMAT_LENGTH_PARAMETER: 'INVALID_FORMAT_LENGTH_PARAMETER',
		INVALID_FORMAT_EQUAL_PARAMETER: 'INVALID_FORMAT_EQUAL_PARAMETER',
		INVALID_PATTERN_PARAMETER: 'INVALID_PATTERN_PARAMETER',
		INVALID_PARAMETER_VALUE: 'INVALID_PARAMETER_VALUE',
		INVALID_$$_VALUE: 'INVALID_$$_VALUE',
		INVALID_$$_STATUS: 'INVALID_$$_STATUS',
		INVALID_$$_PATH: 'INVALID_$$_PATH',

		ILLEGAL_LEADING_TRAILING_CHARACTERS: 'ILLEGAL_LEADING_TRAILING_CHARACTERS',
		$$_ALREADY_EXIST: '$$_ALREADY_EXIST',
		$$_ALREADY_DELETED: '$$_ALREADY_DELETED',
		$$_ALREADY_ACTIVATE: '$$_ALREADY_ACTIVATE',
		$$_ALREADY_EXECUTED: '$$_ALREADY_EXECUTED',
		$$_NOT_FOUND: '$$_NOT_FOUND',
		$$_OUT_OF_RANGE_PARAMETER: '$$_OUT_OF_RANGE_PARAMETER',
		VALUES_ALREADY_EXIST: 'VALUES_ALREADY_EXIST',
		EXCLUSIVE_PARAMETER: 'EXCLUSIVE_PARAMETER',
		NO_SOCKET_ID: 'NO_SOCKET_ID',
		DUPLICATE_EVENT: 'DUPLICATE_EVENT',
		DUPLICATE_EVENTS_SUBSCRIBTION: 'DUPLICATE_EVENTS_SUBSCRIBTION',
		DUPLICATE_KEYS: 'DUPLICATE_KEYS',
		DUPLICATE_KEY_$$: 'DUPLICATE_KEY_$$',

		NO_COMMAND_FOUND: 'COMMAND_NOT_FOUND',
		DEVICE_NOT_CONNECTED: 'DEVICE_NOT_CONNECTED',
		INVALID_DEVICE_$$: 'INVALID_DEVICE_',
		UPDATE_NO_CHANGE: 'UPDATE_NO_CHANGE',
		PAGE_OUT_OF_RANGE: 'PAGE_OUT_O_RANGE',
		QUERY_FIELDS_EMPTY: 'QUERY_FIELDS_EMPTY',
		NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
		REQUEST_TO_DEVICE: 'REQUEST_TO_DEVICE',

		REQUEST_TIMEOUT_$$: 'REQUEST_TIMEOUT_$$',

		$$_CONFLICT: '$$_CONFLICT',

		CANNOT_KILL_WPT_TIMEOUT: 'CANNOT_KILL_WPT_TIMEOUT',
		KILL_WPT_NOT_CONFIRMED: 'KILL_WPT_NOT_CONFIRMED',
		KILL_WPT_WRONG_PLATFORM: 'KILL_WPT_WRONG_PLATFORM',
		WPT_CANNOT_BE_CREATED: 'WPT_CANNOT_BE_CREATED',
		WPT_CREATION_FAILED: "WPT_CREATION_FAILED",

		$$_NOT_AVAILABLE: "$$_NOT_AVAILABLE",
		UPDATE_DOWNLOAD: "UPDATE_DOWNLOAD"
	}
const error_messages = {
	MISSING_MANDATORY_PARAMETER: '$0 is missing',
	$$_NOT_FOUND: '$0 with the $1 $2 was not found',
	PAGE_OUT_OR_RANGE: 'page parameter $0 is out of range. See _meta in the response',
	QUERY_INCLUDES_EMPTY: 'query.includes must not be empty',
	DUPLICATE_KEYS: 'duplicate keys values violates unique constraint',
	DUPLICATE_EVENT: 'event already exist',
	DUPLICATE_KEY_$$: '$0 already exist',
	UPDATE_NO_CHANGE: 'current values are the same as the previous ones',
	DEVICE_NOT_CONNECTED: 'device $0 is not online or not connected to the server',
	$$_ALREADY_EXIST: '$1 with "$2" already exist',
	$$_ALREADY_DELETED: '$1 has already been deleted',
	$$_ALREADY_ACTIVATE: '$1 has already been activated',
	$$_ALREADY_EXECUTED: '$0 $1 has already been executed',
	REQUEST_TO_DEVICE: 'The request to the device $0 failed',
	COMMAND_NOT_FOUND: 'The command $1 not found for terminal.id $2',
	SERVICE_NOT_STARTED: 'The service $1 was not enable to start',
	SERVICE_$$_NOT_AVAILABLE: 'The service $0 is not available',
	// 'id_user_not_found': 'Id user does not exist',
	// 'route_not_found': "'{}' not found",
	// 'unknown_error': 'An unknown error appear. An email was send to an admin',
	// 'user_not_found': 'User not found with this {}',
	// 'access_forbidden': 'User not have the permission to access this route',
	// 'token_expired': 'The token you submitted has expired',
	// 'incorrect_email_or_password': 'Your email or your password is incorrect',
	// 'no_ressource_found': 'No ressource was found with id {}',
}
const httpcodes = new Map([
	[100, 'Continue'],
	[101, 'Switching Protocols'],
	[102, 'Processing'],
	[200, 'OK'],
	[201, 'Created'],
	[202, 'Accepted'],
	[203, 'Non-Authoritative Information'],
	[204, 'No Content'],
	[205, 'Reset Content'],
	[206, 'Partial Content'],
	[207, 'Multi-Status'],
	[300, 'Multiple Choices'],
	[301, 'Moved Permanently'],
	[302, 'Moved Temporarily'],
	[303, 'See Other'],
	[304, 'Not Modified'],
	[305, 'Use Proxy'],
	[307, 'Temporary Redirect'],
	[400, 'Bad Request'],
	[401, 'Unauthorized'],
	[402, 'Payment Required'],
	[403, 'Forbidden'],
	[404, 'Not Found'],
	[405, 'Method Not Allowed'],
	[406, 'Not Acceptable'],
	[407, 'Proxy Authentication Required'],
	[408, 'Request Time-out'],
	[409, 'Conflict'],
	[410, 'Gone'],
	[411, 'Length Required'],
	[412, 'Precondition Failed'],
	[413, 'Request Entity Too Large'],
	[414, 'Request-URI Too Large'],
	[415, 'Unsupported Media Type'],
	[416, 'Requested Range Not Satisfiable'],
	[417, 'Expectation Failed'],
	[418, "I'm a teapot"],
	[422, 'Unprocessable Entity'],
	[423, 'Locked'],
	[424, 'Failed Dependency'],
	[425, 'Unordered Collection'],
	[426, 'Upgrade Required'],
	[428, 'Precondition Required'],
	[429, 'Too Many Requests'],
	[431, 'Request Header Fields Too Large'],
	[451, 'Unavailable For Legal Reasons'],
	[500, 'Internal Server Error'],
	[501, 'Not Implemented'],
	[502, 'Bad Gateway'],
	[503, 'Service Unavailable'],
	[504, 'Gateway Time-out'],
	[505, 'HTTP Version Not Supported'],
	[506, 'Variant Also Negotiates'],
	[507, 'Insufficient Storage'],
	[509, 'Bandwidth Limit Exceeded'],
	[510, 'Not Extended'],
	[511, 'Network Authentication Required'],
])

module.exports = { httpcodes, error_messages, CODE }
