# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Wyndpos electron publish

on:
  create:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm run dist
      - name: Archive pos react artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pos-dist-react
          path: src/pos/dist
          retention-days: 1
      - name: Archive pos react artifacts
        uses: actions/upload-artifact@v2
        with:
          name: loader-dist-react
          path: src/loader/dist
          retention-days: 1
  build:
    needs: dist
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Download pos eact dist
        uses: actions/download-artifact@v2
        with:
          name: pos-dist-react
          path: src/pos/dist
      - name: Download loader react dist
        uses: actions/download-artifact@v2
        with:
          name: loader-dist-react
          path: src/loader/dist
      - run: npm install
      - name: Install electron builder
        run: npm i -g electron-builder
      - run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
